Vagrant.configure("2") do |config|

  config.vm.box = "saucy64"
  config.vm.box_url = "https://s3.amazonaws.com/jedcn-dev-machines/saucy64.box"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--name", "vagrant-saucy-64-dev"]
  end

  config.vm.hostname = 'saucy64-dev'

  config.vm.provision :puppet do |puppet|
    puppet.options = '--verbose'
  end

end
